###
POST http://localhost:8080/api/ai/chatIngestion
Content-Type: application/json

{
  "promptMessage": "I cannot login to the system, which team should I contact? Only respond with the team name."
}
###
Prompts:
"Some pricing are wrong, which team should I contact? Only respond with the team name."
"Provider cannot add invoices to the bills, which team should I contact? Only respond with the team name."
"I cannot login to the system, which team should I contact? Only respond with the team name."