###
POST http://localhost:8080/api/ai/generateGeneral
Content-Type: application/json

{
  "promptMessage": "Tell me a joke about software engineers"
}

###
POST http://localhost:8080/api/ai/generateJsonOutput
Content-Type: application/json

{
  "league": "Premier League",
  "position": "forward"
}

###
POST http://localhost:8080/api/ai/chatIngestion
Content-Type: application/json

{
  "promptMessage": "I cannot login, which team should I contact?"
}